steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops-$BRANCH_NAME", "."]

  # push the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-$BRANCH_NAME"]

  # replace variables in gke.yaml before deployment
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PROJECT_ID=$PROJECT_ID BRANCH_NAME=$BRANCH_NAME envsubst < gke.yaml > gke-processed.yaml

  # deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - apply
  - -f
  - gke-processed.yaml

options:
  logging: CLOUD_LOGGING_ONLY