steps:
  # Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops-$BRANCH_NAME", "."]

  # Push the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-$BRANCH_NAME"]

  # Step to replace variables in the gke.yaml file
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s/\PROJECT_ID/$PROJECT_ID/g" gke.yaml
      sed -i "s/\BRANCH_NAME/$BRANCH_NAME/g" gke.yaml

  # Deploy the container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops-$BRANCH_NAME
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-$BRANCH_NAME

options:
  logging: CLOUD_LOGGING_ONLY